#services:
#  cassandra:
#    image: 'cassandra:latest'
#    environment:
#      - 'CASSANDRA_DC=dc1'
#      - 'CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch'
#    ports:
#      - '9042'
#
#
# execute the command : $docker network create cassandra_cassandra-network
version: '3'
services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042"
    environment:
      - MAX_HEAP_SIZE=256M
      - HEAP_NEWSIZE=100M
      - CASSANDRA_DC=dc1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_KEYSPACE=mykeyspace

    networks:
      - cassandra-network

  dse-studio:
    image: datastax/dse-studio
    container_name: dse-studio
    environment:
      - DS_LICENSE=accept
    depends_on:
      - cassandra
    ports:
      - "9091:9091"
    networks:
      - cassandra-network

networks:
  cassandra-network:

